steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: sh
    secretEnv:
      - SENTRY_DSN
    args:
      - -c
      - >-
        docker build
        --build-arg BASE_IMAGE=${_BASE_IMAGE}
        --build-arg APP_RELEASE=${_APP_RELEASE}
        --build-arg RELEASE_VERSION=${_RELEASE_VERSION}
        --build-arg BUILD_TIME=${_BUILD_TIME}
        --build-arg SENTRY_DSN="$$SENTRY_DSN"
        --tag ${_TARGET_IMAGE}
        .
images:
  - ${_TARGET_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BASE_IMAGE: ''
  _APP_RELEASE: ''
  _RELEASE_VERSION: ''
  _BUILD_TIME: ''
  _TARGET_IMAGE: ''
  _SENTRY_DSN_VERSION: '1'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/lekha-frontend-sentry-dsn/versions/${_SENTRY_DSN_VERSION}
      env: SENTRY_DSN
